@startuml name MedMVP Container
title Медикаменте автоматизация работы с клиентами MVP. 

top to bottom direction

!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(uClient, "Клиент", "Пациент")



System_Ext(lab, "Лабораторяи", "")



System_Boundary(sys, "Медикаменте") {
    Person(uDoc, "Доктор", "Сотрудник-медик")
    Person(uReseption, "Администратор", "Сотрудник ресепшена")
    Container_Boundary(dc1, "Датацентр 1"){
        
        System_Boundary(clientPortal,"Портал клиентов",""){
            System(apiDMZ,"ApiGateway Ext","nginx")
            System_Boundary(k8scp, "k8s"){
                System_Boundary(msClientPortal, "Микросервисы",".net core/java"){
                    System(msDMZClients,"Клиенты", "Сервисы профилей клиентов")
                    System(msDMZCalendar,"Календарь", "Сервис записей клиентов")
                }
            }
            System(mscpCache,"Кэш", "Redis")
            System(mscpDB,"СУБД", "Postgres")
            System(kcDMZ,"Авторизация", "Keycloack")
            Rel(apiDMZ, kcDMZ, "")
            Rel(msClientPortal, kcDMZ, "Получение приватного ключа для проверки JWT")
        }
        

        System_Boundary(resPortal,"Портал Ресепшен",""){
            System(apiLan,"ApiGateway lan","nginx")
            System_Boundary(k8srp, "k8s"){
                System_Boundary(msResPortal, "Микросервисы",".net core/java"){
                    System(msClients,"Клиенты", "Сервисы профилей клиентов")
                    System(msClinicHistory,"Мед карты", "Сервис историй болезни")
                    System(msCalendar,"Календарь", "Сервис записей клиентов")
                }
            }
            System(msrpCache,"Кэш", "Redis")
            System(msrpDB,"СУБД", "Postgres")
            System(kcLan,"Авторизация", "Keycloack")
            Rel(apiLan, kcLan, "")
            
            Rel(msResPortal, kcLan, "Получение приватного ключа для проверки JWT")
            System(ebus,"Шина сообщений","kafka")
        }
      
    }
    System_Boundary(lserver,"Сервер приложений","MS Windows Server 2022"){
        System(ad,"Auth","Active Directory")
        System(fs,"Файловый сервер","File server")
    }   
    System(sysServices,"Системные сервисы","Логирование, журналирование, трассировка")
    Rel(clientPortal, sysServices, "")
    Rel(resPortal, sysServices, "")
}
Rel(uDoc, apiLan,"")
Rel(kcLan, ad, "")
Rel(lab, apiDMZ, "Сохранение результатов анализов")
Rel(uClient, apiDMZ, "Авторизация и получение JWT")
Rel(lab, apiDMZ, "Авторизация и получение JWT")

Rel(uClient, apiDMZ,"https(tls1.3) UC1 записаться на приём к специалисту")
Rel(apiDMZ, msDMZClients,"https(tls1.3 + JWT) Просмотр свох данных, редактирование")
Rel(apiDMZ, msDMZCalendar,"https(tls1.3 + JWT) Получение записей (своих), получение сводного времени специалиста, подача заявки на запись")

Rel(msClientPortal, mscpCache,"Использование кэша")
Rel(msClientPortal, mscpDB,"Использование СУБД")
Rel(msDMZClients, ebus,"Заявки на изменение клиентских данных")
Rel(msDMZCalendar, ebus,"Заявки на запись, получение подтверждения записи, получение доступного времени специалиста")

Rel(apiLan, msClients, "С роолью Доктор (только клиента по Id), Администратор (только клиента по поиску)")
Rel(apiLan, msClinicHistory, "С роолью Доктор (только клиента по Id)")
Rel(apiLan, msCalendar, "С роолью Доктор (Только свои записи), Администратор")

Rel(uReseption, apiLan,"Регистрация пациента")
Rel(uReseption, apiLan,"Отслеживание записи клиента")
Rel(uReseption, uClient,"Напоминание")
Rel(uReseption, uDoc,"Напоминание")
Rel(msResPortal, msrpCache,"Использование кэша")
Rel(msResPortal, msrpDB,"Использование СУБД")

Rel(msClients, ebus,"Регистрация/Обновление пользователей")
Rel(msClinicHistory, ebus,"Получение результатов анализов")
Rel(msCalendar, ebus,"Записи клиентов")


@enduml

